### ISSUE TITLE
AceLocale issue with latest update today

### ISSUE THREAD

**Issue by dblanch369** [casualshammy/DeathNote#10]
I just installed DN 90205.1 from this repo.  Now I am getting all kinds of AceLocale errors.  I use Titan for my LDB and the error occurs when I mouse over Death Note.  Hopefully someone can offer suggestions if this isn't a Deathnote issue by itself.

Here is the main error:

1x AceLocale-3.0-6: DeathNote: Missing entry for 'Click to open Death Note. Right-Click to show options. Shift-Click to optimize data. Ctrl-Click to reset data.'
[string "@DeathNote\DeathNote-90205.1-release.lua"]:58: in function `func'
[string "@Titan\LDBToTitan.lua"]:182: in function `TitanLDBSetTooltip'
[string "@Titan\LDBToTitan.lua"]:246: in function <Titan\LDBToTitan.lua:244>

**Comment by casualshammy** [comment]
Sorry. I've pushed a fix - `90205.2-release`

**Comment by dblanch369** [comment]
The fix is working perfectly.  Thanks!
