### ISSUE TITLE
Wrath Classic version / support / TOC update

### ISSUE THREAD

**Issue by boktai1000** [casualshammy/DeathNote#12]
Hey there,

Just wanted to check if continued support into Wrath Classic was part of the plan, and if not - formally do a feature request for it here :)

Cheers

**Comment by emanueol** [comment]
Also looking to know if this will be updated for classic wotlk ? I really love itl.

**Comment by dblanch369** [comment]
Yes, please updated TOC and packager.  My add-on manager keeps wanting to download the retail version instead of a version packaged for Wrath Classic

**Comment by dblanch369** [comment]
@casualshammy Just a friendly ping to see if you could update the packager for Wrath.

**Comment by casualshammy** [comment]
Hello! I've pushed WotLK version a minute ago. I don't play WotLK (so I cannot test addon continuously), but I've died a couple of times and clicked every control I've found.

**Comment by dblanch369** [comment]
Installed like a charm!  Thank so much good sir!On Sep 22, 2022, at 3:39 PM, casualshammy ***@***.***> wrote:﻿
Hello! I've pushed WotLK version a minute ago. I don't play WotLK, but I've died a couple of times and clicked every control I've found.
