### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Typhosy** [casualshammy/DeathNote#14]
6x DeathNote\Output.lua:46: attempt to call global 'IsPartyLFG' (a nil value)
[string "@DeathNote\Output.lua"]:46: in function `func'
[string "@DeathNote\Output.lua"]:16: in function `O_Send'
[string "@DeathNote\Announce.lua"]:113: in function `AnnounceDeath'
[string "@DeathNote\DataCapture.lua"]:66: in function `AddDeath'
[string "@DeathNote\DataCapture.lua"]:74: in function `handler'
[string "@DeathNote\DataCapture.lua"]:458: in function `CombatLogHandler'
[string "@DeathNote\DataCapture.lua"]:464: in function `?'
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by emanueol** [comment]
confirm same problem:
`Message: Interface\AddOns\DeathNote\Output.lua:48: attempt to call global 'IsPartyLFG' (a nil value)
Time: Sat Sep 24 00:05:52 2022
Count: 14
Stack: Interface\AddOns\DeathNote\Output.lua:48: attempt to call global 'IsPartyLFG' (a nil value)

Locals: <none>`

**Comment by casualshammy** [comment]
Hope this issue in fixed in the latest release (30400.5-release)
