### ISSUE TITLE
No issue. Just question.

### ISSUE THREAD

**Issue by Hollicsh** [casualshammy/DeathNote#15]
Is there an update planned for version 10.0.0 prepatch ?

**Comment by casualshammy** [comment]
I'll push (probably) working version tonight

**Comment by picklerick84** [comment]
Just fyi.  The current version it is showing on curseforge at least is 1.0.0.  I know its an easy fix for someone to make on their own to add the extra 0, but I don't think very many people feel comfortable making it.
