### ISSUE TITLE
DeathNote Errors [10.0.2 Retail]

### ISSUE THREAD

**Issue by Hollicsh** [casualshammy/DeathNote#16]
1x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "WEEKLY_REWARDS_HIDE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/DeathNote/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <.../AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/DeathNote/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <.../AddOns/DeathNote/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by casualshammy** [comment]
Hello. How to reproduce this bug?

**Comment by Hollicsh** [comment]
Oh shit, sorry, there was my mistake in editing another addon ..
Sorry please ((
