### ISSUE TITLE
call method 'SetHyperlink' (a nil value)

### ISSUE THREAD

**Issue by rml9ty** [casualshammy/DeathNote#17]
I'm on Version: 100000.0-release on retail.

23x DeathNote/Format.lua:596: attempt to call method 'SetHyperlink' (a nil value)
[string "@DeathNote/Format.lua"]:596: in function `FormatTooltipSource'
[string "@DeathNote/UI.lua"]:1122: in function `column_onenter'
[string "@DeathNote/UI.lua"]:2198: in function <DeathNote/UI.lua:2190>

Locals:
self = <table> {
 FormatChatTimestamp = <function> defined @DeathNote/Format.lua:485
 FormatChatSource = <function> defined @DeathNote/Format.lua:534
 ResetData = <function> defined @DeathNote/DataCapture.lua:203
 ToolsDropDownInitialize = <function> defined @DeathNote/UI.lua:1480
 CancelTimer = <function> defined @ArkInventory/Externals/Ace3/AceTimer/AceTimer-3.0.lua:147
 SecureHook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:335
 DataCapture_Initialize = <function> defined @DeathNote/DataCapture.lua:172
 PLAYER_REGEN_DISABLED = <function> defined @DeathNote/DataCapture.lua:350
 auras_tab = <table> {
 }
 FormatTooltipAmount = <function> defined @DeathNote/Format.lua:561
 GetNameButtonHeight = <function> defined @DeathNote/UI.lua:1609
 FormatTooltipHealth = <function> defined @DeathNote/Format.lua:552
 FormatCombatLog = <function> defined @DeathNote/Format.lua:515
 ScheduleTimer = <function> defined @ArkInventory/Externals/Ace3/AceTimer/AceTimer-3.0.lua:94
 RegisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:148
 EntryIndexInfo = <table> {
 }
 CreateListBox = <function> defined @DeathNote/UI.lua:2480
 FormatTooltipHealthGroup = <function> defined @DeathNote/Format.lua:627
 auras_tab_spacer1 = Texture {
 }
 db = <table> {
 }
 IterateDeath = <function> defined @DeathNote/Data.lua:31
 damage_tab = <table> {
 }
 SetEnabledState = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:273
 Options = <table> {
 }
 AddSpellFilter = <function> defined @DeathNote/UI.lua:1972
 CycleTimestampDisplay = <function> defined @DeathNote/Format.lua:443
 OnEnable = <function> defined @DeathNote/DeathNote.lua:74
 CurrentDataVersion = 1
 AnnounceDeath = <function> defined @DeathNote/Announce.lua:7
 GetAmountFunc = <function> defined @DeathNote/Data.lua:252
 CleanForChat = <function> defined @DeathNote/Format.lua:504
 CycleHealthDisplay = <function> defined @DeathNote/Format.lua:447
 ShowToolsMenu = <function> defined @DeathNote/UI.lua:1470
 IsGroupOverThreshold = <function> defined @DeathNote/Data.lua:288
 OnInitialize = <function> defined @DeathNote/DeathNote.lua:9
 NewModule = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:231
 SetFiltersTab = <function> defined @DeathNote/UI.lua:1155
 FormatGroupEntry = <function> defined @DeathNote/Format.lua:854
 FormatReportCompact = <function> defined @DeathNote/Format.lua:891
 FormatUnit = <function> defined @DeathNote/Format.lua:103
 UpdateNameList = <function> defined @DeathNote/UI.lua:1706
 GetName = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 ShowFiltersTab = <function> defined @DeathNote/UI.lua:1233
 SetSpellHilight = <function> defined @DeathNote/UI.lua:2000
 name = "DeathNote"
 ldb = <table> {
 }
 IsTypeConsolidated = <function> defined @DeathNote/UI.lua:1781
 Disable = <function> defined @Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 Unhook = <function> defined @ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:417
 Print = <function> defined @DeathNote/DeathNote.lua:98
 filters_tab = DeathNoteFilters {
 }
 FormatTooltipSourceGroup = <function> defined @DeathN

**Comment by casualshammy** [comment]
I hope this bug is fixed in `100002.2-release`
