### ISSUE TITLE
Errors whenever using addon to look up death

### ISSUE THREAD

**Issue by picklerick84** [casualshammy/DeathNote#20]
Is this addon going to be updated?  It hasn't been update except the toc, and the toc was updated to 1.0.0, not 10.0.0.  Easy fix.  But I get this error whenever looking up a death:

1390x DeathNote/Format.lua:596: attempt to call method 'SetHyperlink' (a nil value)
[string "@DeathNote/Format.lua"]:596: in function `FormatTooltipSource'
[string "@DeathNote/UI.lua"]:1122: in function `column_onenter'
[string "@DeathNote/UI.lua"]:2198: in function <DeathNote/UI.lua:2190>

Locals:
Skipped (In Encounter)

**Comment by Snichy** [comment]
I get this too - would love an official fix!

**Comment by casualshammy** [comment]
I hope this bug is fixed in `100002.2-release`
