### ISSUE TITLE
Game version is not correct in curseforge xD

### ISSUE THREAD

**Issue by Seventii** [casualshammy/DeathNote#29]
hi
it should be 11.0xxx right ?
but its not xD its not any issue anyway just letting u know xD
![Untitled3213](https://github.com/user-attachments/assets/980c1d7b-484b-4856-9523-b7a0c138d471)

**Comment by casualshammy** [comment]
Hi,
Seems like there is some sort of bug in curseforge. I've changed game version manually. Thank you!
