### ISSUE TITLE
[LUA Error] Patch 9.1

### ISSUE THREAD

**Issue by Merxxz** [casualshammy/DeathNote#5]
```
4x DeathNote\Format.lua:193: attempt to index local 'colorArray' (a nil value)
[string "@DeathNote\Format.lua"]:193: in function <DeathNote\Format.lua:191>
[string "@DeathNote\Format.lua"]:234: in function `?'
[string "@DeathNote\Format.lua"]:456: in function `FormatEntrySpell'
[string "@DeathNote\Format.lua"]:474: in function `FormatNameListEntry'
[string "@DeathNote\UI.lua"]:1769: in function `?'
[string "@DeathNote\UI.lua"]:1152: in function `Show'
[string "@DeathNote\UI.lua"]:1244: in function `ShowUnit'
[string "@DeathNote\UI.lua"]:1302: in function `func'
[string "@SharedXML\UIDropDownMenu.lua"]:912: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
colorArray = nil
(*temporary) = <function> defined @Blizzard_CombatLog\Blizzard_CombatLog.lua:1709
(*temporary) = <table> {
 settings = <table> {
 }
 hasQuickButton = true
 quickButtonDisplay = <table> {
 }
 colors = <table> {
 }
 filters = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'colorArray' (a nil value)"
```

**Comment by Translitdk** [comment]
change line 193 at DeathNote\Format.lua from
`local colorArray = CombatLog_Color_ColorArrayBySchool(SCHOOL_MASK_PHYSICAL, DEFAULT_COMBATLOG_FILTER_TEMPLATE)`
to
`local colorArray = CombatLog_Color_ColorArrayBySchool(Enum.Damageclass.MaskPhysical, DEFAULT_COMBATLOG_FILTER_TEMPLATE)`

**Comment by Merxxz** [comment]
> 
> 
> change line 193 at DeathNote\Format.lua from
> `local colorArray = CombatLog_Color_ColorArrayBySchool(SCHOOL_MASK_PHYSICAL, DEFAULT_COMBATLOG_FILTER_TEMPLATE)`
> to
> `local colorArray = CombatLog_Color_ColorArrayBySchool(Enum.Damageclass.MaskPhysical, DEFAULT_COMBATLOG_FILTER_TEMPLATE)`

This worked. Checked Townlong-Yak and indeed the constants got changed. See the two links below.
[9.0.5 - COMBATLOG_DEFAULT_COLORS.schoolColoring](https://www.townlong-yak.com/framexml/9.0.5/Blizzard_CombatLog/Blizzard_CombatLog.lua#45)
[9.1.0 - COMBATLOG_DEFAULT_COLORS.schoolColoring](https://www.townlong-yak.com/framexml/live/Blizzard_CombatLog/Blizzard_CombatLog.lua#45)
