### ISSUE TITLE
SPELL_DISPEL_FAILED event causes error in TBC classic

### ISSUE THREAD

**Issue by fabbew** [casualshammy/DeathNote#7]
https://github.com/casualshammy/DeathNote/blob/1bf7d3e63a89fc340cf7ffbb869d898d240575a1/Data.lua#L165

I have for a while noticed that I am not able to properly see some death (somewhat randomly) because of an error and did some digging;

It is the SPELL_DISPEL_FAILED combat log event that causes errors to occur since the addon cannot parse the deaths with this event, since the type is missing.

I simply replaced it with the same type as SPELL_DISPEL; since the dispels are not actually shown anyway we just need it to not cause an error.

["SPELL_DISPEL"]			= { TypeAura, nil, nil, ExtraSpellId, AuraDispel },
["SPELL_DISPEL_FAILED"]		= { TypeAura, nil, nil, ExtraSpellId, AuraDispel },

**Comment by fabbew** [comment]
![image](https://user-images.githubusercontent.com/80228002/154969742-55cf86ee-d368-4aaf-8b2f-5e116fb15d39.png)

**Comment by casualshammy** [comment]
Thanks for your contrubution!
