### ISSUE TITLE
unit popup menu

### ISSUE THREAD

**Issue by CoachX** [casualshammy/DeathNote#9]
166x DeathNote\UI.lua:1263: attempt to index global 'UnitPopupButtons' (a nil value)
[string "@DeathNote\UI.lua"]:1263: in function `AddToUnitPopup'
[string "@DeathNote\DeathNote-90100.0-release.lua"]:85: in function <DeathNote\DeathNote.lua:74>
[string "=[C]"]: ?
[string "@DeathNote\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DeathNote\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DeathNote\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DeathNote\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DeathNote\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

no deathnote option on menu drop down

**Comment by casualshammy** [comment]
Fixed in `90205.1-release`
